commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("active_listing", views.active_listing, name="active_listing"),
    path("auction_view/<int:pk>", views.auction_view, name="auction_view"),
    path("categories", views.categories, name="categories"),
    path("category_listing/<str:cat>", views.category_listing, name="category_listing"),
    path("close_auction/<int:pk>", views.close_auction, name="close_auction"),
    path("wishlist/<int:pk>", views.wishlist, name="wishlist"),
    path("bookmarks", views.bookmarks, name="bookmarks"),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.conf import settings


class User(AbstractUser):
    pass

class AuctionListing(models.Model):
    # Define fields for auction listing model
    title = models.CharField(max_length=100)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2)
    current_bid = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=50)
    image_url = models.URLField(null = True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    favoured = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_favoured", blank=True)
    
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.current_bid = self.starting_bid
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('auction_view', kwargs={"pk": self.pk})
    

class Bid(models.Model):
    # Define fields for bid model
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.bid_amount} bid on {self.listing} by {self.bidder}"

class Comment(models.Model):
    # Define fields for comment model
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE)
    commenter = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"{self.commenter} comment on {self.listing}"
    
    
class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(null=False, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse('category_listings', kwargs={'slug': self.slug})

commerce/auctions/forms.py
from django import forms
from auctions.models import AuctionListing, Bid, Comment


class NewListingForm(forms.ModelForm):
    image_url = forms.URLField(required=False) 
    class Meta:
        model = AuctionListing
        fields = ['title', 'description', 'category', 'image_url', 'starting_bid']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter title'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
            'category': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter category'}),
            'image_url': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter image URL'}),
            'starting_bid': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter starting bid'}),
        }
        


class BidForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.listing = kwargs.pop('listing')
        super(BidForm, self).__init__(*args, **kwargs)

    def clean(self):
        amount = self.cleaned_data['bid_amount']
        if amount <= self.listing.current_bid:
            raise forms.ValidationError("Your bid is lower than current bid")

        return self.cleaned_data

    class Meta:
        model = Bid
        fields = ['bid_amount']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your comment'})
        }

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render ,redirect
from django.urls import reverse
from .forms import *
from decimal import Decimal
from .models import *


def index(request):
    return redirect('active_listing')

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect("active_listing")
        else:
            return render(
                request,
                "auctions/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect("active_listing")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request, "auctions/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


def create_listing(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    if request.method == "POST":
        form = NewListingForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.created_by = request.user
            obj.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        form = NewListingForm
        return render(request, "auctions/create_listing.html", {"form": form})


def active_listing(request):
    listings = AuctionListing.objects.filter(active=True)
    listings_end = AuctionListing.objects.filter(active=False)
    
    for list in listings:
        print("---->", list)
    return render(request, "auctions/index.html", {"listings": listings,"listings_end":listings_end})


def categories(request):
    categories = AuctionListing.objects.values_list("category", flat=True).distinct()

    print(categories)
    return render(request, "auctions/categories.html", {"categories": categories})


def category_listing(request, cat):
    listings = AuctionListing.objects.filter(category=cat)
    return render(request, "auctions/index.html", {"listings": listings, "cat": cat})


def close_auction(request, pk):
    auction = AuctionListing.objects.get(id=pk)
    if request.user.is_authenticated and auction.created_by == request.user:
        # user is authenticated, and owner of that auction
        auction.active = False
        auction.save()

    return HttpResponseRedirect(reverse("auction_view", args=[pk]))


def auction_view(request, pk):
    listing = AuctionListing.objects.get(id=pk)
    if request.user.is_authenticated:
        try:
            top_bid = Bid.objects.filter(listing=listing.id).order_by("-bid_amount")[0]
        except:
            top_bid = None

        if request.method == "POST":
            if "bid" in request.POST:
                bid_form = BidForm(request.POST, listing=listing)
                if bid_form.is_valid() and request.user.is_authenticated:
                    temp = bid_form.save(commit=False)
                    temp.bidder = request.user
                    temp.listing = listing
                    temp.save()
                    listing.current_bid = temp.bid_amount
                    listing.save()
                    return redirect(auction_view, pk=listing.pk)

        # new comment was submitted
            elif "comment" in request.POST:
                comment_form = CommentForm(request.POST)
                if comment_form.is_valid() and request.user.is_authenticated:
                    temp = comment_form.save(commit=False)
                    temp.commenter = request.user
                    temp.listing = listing
                    temp.save()
                    return redirect(auction_view, pk=listing.pk)

        else:
            
            form_comment = CommentForm()
            minimum_bid = listing.current_bid + Decimal(0.01).quantize(Decimal("1.00"))
            bid_form = BidForm(initial={"amount": minimum_bid}, listing=listing)

            bids = Bid.objects.filter(listing=listing.id).order_by("-bid_amount")
            comments = Comment.objects.filter(listing=listing)
            
            auction = AuctionListing.objects.get(pk=pk)
            if request.user in auction.favoured.all():
            # User already favoured, unfavourite auction
                fav = True
            else:
            # add auction to favourites
                fav = False

            print("----->", listing)
            return render(
                request,
                "auctions/specific_listing.html",
                {
                    "listing": listing,
                    "form_comment": form_comment,
                    "bids": bids,
                    "top_bid": top_bid,
                    "min_bid": minimum_bid,
                    "bid_form": bid_form,
                    "comments": comments,
                    "fav":fav,
                },
            )
    else:
        return HttpResponseRedirect(reverse("login"))

def wishlist(request,pk):
    if request.user.is_authenticated:
        auction = AuctionListing.objects.get(pk=pk)
        if request.user in auction.favoured.all():
            # User already favoured, unfavourite auction
            auction.favoured.remove(request.user)
        else:
            # add auction to favourites
            auction.favoured.add(request.user)
    return HttpResponseRedirect(reverse("auction_view", args=[pk]))

def bookmarks(request):
    if request.user.is_authenticated:
        auctions = AuctionListing.objects.filter(favoured=request.user)
        return render(request, "auctions/bookmark.html", {"listings": auctions})
    else:
        return HttpResponseRedirect(reverse("login"))

commerce/auctions/templates/auctions/bookmark.html
{% extends "auctions/layout.html" %}

{% block body %}
<div style="min-height:80vh">
<div class="container py-4 py-xl-5">
    <div class="row mb-5">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
            {% if not cat %}
            <h4>Bookmarks</h4>
            {% else %}
            <h4>Category: <strong>{{ cat }}</strong></h4>
            {% endif %}
        </div>
    </div>
    <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
        {% for listing in listings %}
        <div class="col">
            <div class="card"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;"
                    src="{{ listing.image_url }}" />
                <div class="card-body p-4">
                    <div class="card-title"><a href="{% url "auction_view" pk=listing.id %}">{{ listing.title }}</a>
                    </div>
                    <hr>
                    <p class="card-text">{{ listing.description }}</p>
                    <hr>
                    <div class="d-flex">
                        <span>Current price: ${{ listing.current_bid }}</span>
                        <div class="card-body d-flex flex-column align-items-center"></div>
                        
                        {% if listing.active %}
                        <a href="{% url "auction_view" pk=listing.id %}" class="btn btn-primary">Bid</a>
                        {% endif %}
                            
                       
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container py-4 py-xl-5">
    <div class="row mb-5">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
            <h4>Categories</h4>
        </div>
    </div>

    <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
        {% for category in categories %}
        <div class="col">
            <div class="card">
                <div class="card-body p-4">
                    <div class="card-title">
                        <a href="{% url 'category_listing' cat=category %}">{{ category }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div style="height:10rem;"></div>
<div class="card-body d-flex flex-column align-items-center">
    <h4>Listing Form</h4>
    <form action="{% url 'create_listing' %}" method="post" class="listing-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title" class="form-label"><strong>Title:</strong></label>
        </br>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description" class="form-label"><strong>Description:</strong></label>
        </br>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_category" class="form-label"><strong>Category:</strong></label></br>
            {{ form.category }}
        </div>
        <div class="form-group">
            <label for="id_image_url" class="form-label"><strong>Image URL:</strong></label></br>
            {{ form.image_url }}
        </div>
        <div class="form-group">
            <label for="id_starting_bid" class="form-label"><strong>Starting Bid:</strong></label></br>
            {{ form.starting_bid }}
        </div>
        <button class="btn btn-primary" type="submit" name="action" style ="margin-top:2rem;">Add</button>
    </form>
</div>
{% endblock %}

commerce/auctions/templates/auctions/footer.html
<footer class="text-center bg-dark" >
    <div class="container text-white py-4 py-lg-5" style="height: 10vh;">
        <ul class="list-inline">
            <li class="list-inline-item me-4"><a class="link-light" href="#">Created By Abhinav Pangaria for CS50WEB </a></li>
        </ul>
    </div>
</footer>

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container py-4 py-xl-5">
    <div class="row mb-5">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
            {% if not cat %}
            <h4>Active Listing</h4>
            {% else %}
            <h4>Category: <strong>{{ cat }}</strong></h4>
            {% endif %}
        </div>
    </div>
    <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
        {% for listing in listings %}
        <div class="col">
            <div class="card"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;"
                    src="{{ listing.image_url }}" />
                <div class="card-body p-4">
                    <div class="card-title"><a href="{% url "auction_view" pk=listing.id %}">{{ listing.title }}</a>
                    </div>
                    <hr>
                    <p class="card-text">{{ listing.description }}</p>
                    <hr>
                    <div class="d-flex">
                        <span>Current price: ${{ listing.current_bid }}</span>
                        <div class="card-body d-flex flex-column align-items-center"></div>
                        <a href="{% url "auction_view" pk=listing.id %}" class="btn btn-primary">Bid</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr><hr>
    
        <h4>Closed Listing</h4>
        <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
        {% for listing in listings_end %}
        <div class="col">
            <div class="card"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;"
                    src="{{ listing.image_url }}" />
                <div class="card-body p-4">
                    <div class="card-title"><a href="{% url "auction_view" pk=listing.id %}">{{ listing.title }}</a>
                    </div>
                    <hr>
                    <p class="card-text">{{ listing.description }}</p>
                    <hr>
                    <div class="d-flex">
                        <span>Current price: ${{ listing.current_bid }}</span>           
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">

</head>

<body>

<div style="margin-bottom:3rem">
    <nav class="navbar navbar-expand-md bg-dark py-3" data-bs-theme="dark">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'active_listing' %}"><span><strong>Auctions</strong></span></a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div id="navcol-1" class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'active_listing' %}">Active Listings</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bookmarks' %}">WatchList</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'categories' %}">Category Listing</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                <span style="color: aliceblue;"> Logged_In as: {{request.user}}</span>
                {% endif %}
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

</div>

</body>
<footer>
    {% include 'auctions/footer.html' %}
</footer>

</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}


<div style="min-height:80vh">
{% if message %}
<div>{{ message }}</div>
{% endif %}
<div style="height:10rem;"></div>
<div class="card-body d-flex flex-column align-items-center">
    <h4>Login</h4>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="card-body d-flex flex-column align-items-center">
            <input class="btn btn-primary" style="margin-top:2rem;" type="submit" value="Login">
        </div>
    </form>

    <span style="margin-top:2rem;">Don't have an account? <a href="{% url 'register' %}">Register here.</a></span>
</div>
</div>
</div>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}



<div style="min-height:80vh">
{% if message %}
<div>{{ message }}</div>
{% endif %}
<div style="height:10rem;"></div>
<div class="card-body d-flex flex-column align-items-center">
    <h4>Register</h4>
    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <div class="card-body d-flex flex-column align-items-center">
        <input class="btn btn-primary" style="margin-top:2rem;" type="submit" value="Register">
        </div>
    </form>
</br>

   <span style="margin-top:2rem;">Already have an account? <a href="{% url 'login' %}">Log In here.</a></span> 
   </div>
</div>
</div>

{% endblock %}

commerce/auctions/templates/auctions/specific_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div style="height:5rem;"></div>
    <div class="card-body d-flex flex-column align-items-center">
        <form action="{% url 'wishlist' pk=listing.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">{% if fav %}Remove from WatchList{% else %}Add to WatchList{% endif %}</button>
        </form>
</div>

<div style="height: 2rem;"></div>
<div class="card-body d-flex flex-column align-items-center">
    <h4>Listing Page</h4>
    <div class="card" style="margin-top:3rem;"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;"
            src="{{ listing.image_url }}" />
        <div class="card-body p-4">
            <div class="card-title"><a href="{% url 'auction_view' pk=listing.id %}">{{ listing.title }}</a></div>
            <hr>
            <p class="card-text">{{ listing.description }}</p>
            <hr>
        <div class="card-title"><a href="{% url 'category_listing' cat=listing.category %}">{{ listing.category }}</a></div>
            <hr>
            <div class="d-flex">
                <span>Current price: ${{ listing.current_bid }}</span>
            </div>
            <hr>
            <div class="d-flex">
                <span>Listed by: {{ listing.created_by }}</span>
            </div>
        </div>
    </div>
</div>

{% if listing.created_by == request.user %}
<hr>
{% if listing.active %}
<div class="card-body d-flex flex-column align-items-center">
    <h4>Close Auction</h4>
    <div class="card" style="margin-top:3rem; margin-bottom:2rem;">
        <div class="card-body p-4">
            <p class="card-text">Starting Bid : ${{ listing.starting_bid }} <br> Current_Bid :
                ${{ listing.current_bid }}</p>
        </div>
    </div>
    <div>
        <form action="{% url 'close_auction' pk=listing.id %}">
             {% csrf_token %}
            <button type="submit" class="btn btn-danger">Close Auction</button>
        </form>
    </div>

</div>
{% else %}
<div class="alert alert-danger" role="alert">
    You have closed the auction!
    <p>The winning bid was ${{ top_bid.bid_amount }} by {{ top_bid.bidder }}</p>
</div>

{% endif %}


{% else %}

    {% if listing.active %}
    <hr>
    <div class="card" style="margin-top:3rem; margin-bottom:2rem;">
        <div class="card-body p-4">
            <p class="card-text">Starting Bid : ${{ listing.starting_bid }} <br> Current_Bid :
                ${{ listing.current_bid }}
                <br> Minimum_Bid :
                ${{ min_bid }}
            </p>
        </div>
    </div>

    <div style="height:5rem;"></div>
    <div class="card-body d-flex flex-column align-items-center">
        <h4 class="card-text">Biding Form</h4>
        <div style="height: 2rem;"></div>
        <form action="{% url 'auction_view' pk=listing.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title" class="form-label"><strong>Biding Amount:</strong></label>
                </br>
                {{ bid_form.bid_amount }}
            </div>
            <div style="height: 1rem;"></div>

            <button type="submit" class="btn btn-primary" name='bid'>Submit</button>
        </form>
    </div>


    <hr>


    <div style="height:2rem;"></div>
    <div class="card-body d-flex flex-column align-items-center">
        <h4 class="card-text">Comments</h4>
        <div style="height: 2rem;"></div>
        <form action="{% url 'auction_view' pk=listing.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title" class="form-label"><strong>Comment:</strong></label>
                </br>
                {{ form_comment.content }}
            </div>
            <div style="height: 1rem;"></div>

            <button type="submit" class="btn btn-primary" name='comment'>Submit</button>
        </form>
    </div>

    <div style="height:2rem;"></div>

    {% else %}
    <hr>
    <hr>
    {% if top_bid.bidder == request.user %}
    <div class="alert alert-success" role="alert">
        You have won the auction!
    </div>
    {% else %}
    <div class="alert alert-danger" role="alert">
        You have lost the auction!
        <p>The winning bid was ${{ top_bid.bid_amount }} by {{ top_bid.bidder }}</p>
    </div>
    {% endif %}

    {% endif %}

    {% endif %}
    <hr>
    <hr>
    <h5>Recent Comments</h5>
    <div class="container">
    {% if not comments %}
       <h6>No Comment Yet</h6>
        
    {% endif %}
        
    {% for comm in comments %}  
    <div class="card" style="margin-top:1rem; margin-bottom:1rem;">
        <div class="card-body p-4">
            <p class="card-text">Comment : {{ comm.content }} <br> By : {{ comm.commenter }}
                <br> On : {{ comm.created_at }}
            </p>
        </div>
    </div>
    
        {% endfor %}

    </div>
    
    {% endblock %}

    